"""Phoebe UR5e arm models for CERG.

Two separate 6-DOF RobotModel instances — one per arm.
Each loads its own standalone MuJoCo XML (generated by build_arm_xml.py).

Joint ordering (matches the extracted XML, same for both arms):
  0  *_shoulder_pan_joint   revolute  ±2π  150 Nm
  1  *_shoulder_lift_joint  revolute  ±2π  150 Nm
  2  *_elbow_joint          revolute  ±π   150 Nm
  3  *_wrist_1_joint        revolute  ±2π   28 Nm
  4  *_wrist_2_joint        revolute  ±2π   28 Nm
  5  *_wrist_3_joint        revolute  ±2π   28 Nm

Regenerate the XML files with:
    python examples/build_arm_xml.py \\
        --source /path/to/phoebe.xml \\
        --body left_ur_arm_shoulder_link \\
        --output examples/phoebe/models/phoebe_left_arm.xml \\
        --mount-pos "0 0.201 0.85" \\
        --exclude-bodies left_finger_1_link left_finger_2_link

    python examples/build_arm_xml.py \\
        --source /path/to/phoebe.xml \\
        --body right_ur_arm_shoulder_link \\
        --output examples/phoebe/models/phoebe_right_arm.xml \\
        --mount-pos "0 -0.201 0.85" \\
        --exclude-bodies right_finger_1_link right_finger_2_link
"""

from __future__ import annotations

import math
from pathlib import Path

from cerg.core.robot import JointInfo, RobotModel

_HERE = Path(__file__).resolve().parent

_TWO_PI = 2 * math.pi
_PI = math.pi

# Joint specs shared by both UR5e arms
_ARM_JOINTS_TEMPLATE = [
    # (suffix,                 lower,    upper,    max_torque, max_velocity, damping)
    # UR5e datasheet: 150 Nm shoulder/elbow, 28 Nm wrists; 180 deg/s = 3.1416 rad/s all joints
    ("shoulder_pan_joint",  -_TWO_PI, _TWO_PI, 150.0, 3.1416, 1.0),
    ("shoulder_lift_joint", -_TWO_PI, _TWO_PI, 150.0, 3.1416, 1.0),
    ("elbow_joint",         -_PI,     _PI,     150.0, 3.1416, 1.0),
    ("wrist_1_joint",       -_TWO_PI, _TWO_PI,  28.0, 3.1416, 0.5),
    ("wrist_2_joint",       -_TWO_PI, _TWO_PI,  28.0, 3.1416, 0.5),
    ("wrist_3_joint",       -_TWO_PI, _TWO_PI,  28.0, 3.1416, 0.5),
]

_ARM_LINKS_TEMPLATE = [
    "shoulder_link",
    "upper_arm_link",
    "forearm_link",
    "wrist_1_link",
    "wrist_2_link",
    "wrist_3_link",
]


class _PhoebeArmRobot(RobotModel):
    """Base class for a single Phoebe UR5e arm."""

    def __init__(self, side: str) -> None:
        assert side in ("left", "right")
        self._side = side
        self._prefix = f"{side}_ur_arm_"

    @property
    def name(self) -> str:
        return f"phoebe_{self._side}_arm"

    @property
    def nq(self) -> int:
        return 6

    @property
    def nv(self) -> int:
        return 6

    @property
    def joints(self) -> list[JointInfo]:
        return [
            JointInfo(
                name=self._prefix + suffix,
                lower=lower, upper=upper,
                max_torque=max_tau, max_velocity=max_vel, damping=damp,
            )
            for suffix, lower, upper, max_tau, max_vel, damp in _ARM_JOINTS_TEMPLATE
        ]

    @property
    def body_names(self) -> list[str]:
        return [self._prefix + link for link in _ARM_LINKS_TEMPLATE]

    @property
    def end_effectors(self) -> list[str]:
        return [self._prefix + "wrist_3_link"]

    def urdf_path(self) -> Path | None:
        return None

    def mjcf_path(self) -> Path | None:
        p = _HERE / "models" / f"phoebe_{self._side}_arm.xml"
        return p if p.exists() else None


class PhoebeLeftArmRobot(_PhoebeArmRobot):
    """Left Phoebe UR5e arm (6 DOF)."""

    def __init__(self) -> None:
        super().__init__("left")


class PhoebeRightArmRobot(_PhoebeArmRobot):
    """Right Phoebe UR5e arm (6 DOF)."""

    def __init__(self) -> None:
        super().__init__("right")
